
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'APERTURA BIN CADENA CICLO CIERRE COMA COMENTARIO CONTADOR DEC EJE ENT FALSE IDENTIFICADOR IGUAL LPAREN MOTORX MOTORY NO NODO NUMERO OBJETO PROG PROG PUEDE RELOJ RPAREN RUTINA SI TEMPO TIENE TRUE opARITMETICO opLOGICO\nprograma : PROG IDENTIFICADOR APERTURA bloque_codigo CIERRE\n\nbloque_codigo : declaracion\n              | bloque_codigo declaracion\n\ndeclaracion : constructor_base\n            | modificador_caracteristica\n            | rutina\n\nconstructor_base : NODO IDENTIFICADOR OBJETO APERTURA bloque_caracteristicas CIERRE\n\nbloque_caracteristicas : caracteristica\n                       | bloque_caracteristicas caracteristica\n\ncaracteristica : TIENE APERTURA bloque_tiene CIERRE\n               | PUEDE APERTURA bloque_puede CIERRE\n\nbloque_tiene : asignacion\n             | bloque_tiene asignacion\n\nasignacion : assign_type IDENTIFICADOR IGUAL NUMERO\n\nassign_type : IDENTIFICADOR\n            | EJE\n            | MOTORX\n            | MOTORY\n\nbloque_puede : funcion\n             | bloque_puede funcion\n\nrutina : RUTINA IDENTIFICADOR APERTURA bloque_puede CIERRE\n\nfuncion : IDENTIFICADOR LPAREN argumentos RPAREN\n\nargumentos : argumento\n           | argumentos COMA argumento\n\nargumento : IDENTIFICADOR\n          | NUMERO\n\nmodificador_caracteristica : IDENTIFICADOR TIENE APERTURA bloque_tiene CIERRE\n                           | IDENTIFICADOR PUEDE APERTURA bloque_puede CIERRE\n'
    
_lr_action_items = {'PROG':([0,],[2,]),'$end':([1,15,],[0,-1,]),'IDENTIFICADOR':([2,4,6,7,8,9,10,11,12,16,19,20,22,23,24,25,26,27,28,29,31,32,34,35,36,38,39,40,45,51,53,54,55,56,57,58,59,],[3,5,5,-2,-4,-5,-6,17,18,-3,23,30,30,-15,23,-12,37,-16,-17,-18,30,-19,30,-27,-13,47,-28,-20,-21,-7,23,30,-14,-22,47,23,30,]),'APERTURA':([3,13,14,18,21,43,44,],[4,19,20,22,33,53,54,]),'NODO':([4,6,7,8,9,10,16,35,39,45,51,],[11,11,-2,-4,-5,-6,-3,-27,-28,-21,-7,]),'RUTINA':([4,6,7,8,9,10,16,35,39,45,51,],[12,12,-2,-4,-5,-6,-3,-27,-28,-21,-7,]),'TIENE':([5,33,41,42,52,61,62,],[13,43,43,-8,-9,-10,-11,]),'PUEDE':([5,33,41,42,52,61,62,],[14,44,44,-8,-9,-10,-11,]),'CIERRE':([6,7,8,9,10,16,24,25,31,32,34,35,36,39,40,41,42,45,51,52,55,56,58,59,61,62,],[15,-2,-4,-5,-6,-3,35,-12,39,-19,45,-27,-13,-28,-20,51,-8,-21,-7,-9,-14,-22,61,62,-10,-11,]),'OBJETO':([17,],[21,]),'EJE':([19,24,25,36,53,55,58,],[27,27,-12,-13,27,-14,27,]),'MOTORX':([19,24,25,36,53,55,58,],[28,28,-12,-13,28,-14,28,]),'MOTORY':([19,24,25,36,53,55,58,],[29,29,-12,-13,29,-14,29,]),'LPAREN':([30,],[38,]),'IGUAL':([37,],[46,]),'NUMERO':([38,46,57,],[50,55,50,]),'RPAREN':([47,48,49,50,60,],[-25,56,-23,-26,-24,]),'COMA':([47,48,49,50,60,],[-25,57,-23,-26,-24,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'programa':([0,],[1,]),'bloque_codigo':([4,],[6,]),'declaracion':([4,6,],[7,16,]),'constructor_base':([4,6,],[8,8,]),'modificador_caracteristica':([4,6,],[9,9,]),'rutina':([4,6,],[10,10,]),'bloque_tiene':([19,53,],[24,58,]),'asignacion':([19,24,53,58,],[25,36,25,36,]),'assign_type':([19,24,53,58,],[26,26,26,26,]),'bloque_puede':([20,22,54,],[31,34,59,]),'funcion':([20,22,31,34,54,59,],[32,32,40,40,32,40,]),'bloque_caracteristicas':([33,],[41,]),'caracteristica':([33,41,],[42,52,]),'argumentos':([38,],[48,]),'argumento':([38,57,],[49,60,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> programa","S'",1,None,None,None),
  ('programa -> PROG IDENTIFICADOR APERTURA bloque_codigo CIERRE','programa',5,'p_programa','sintactico.py',16),
  ('bloque_codigo -> declaracion','bloque_codigo',1,'p_bloque_codigo','sintactico.py',22),
  ('bloque_codigo -> bloque_codigo declaracion','bloque_codigo',2,'p_bloque_codigo','sintactico.py',23),
  ('declaracion -> constructor_base','declaracion',1,'p_declaracion','sintactico.py',32),
  ('declaracion -> modificador_caracteristica','declaracion',1,'p_declaracion','sintactico.py',33),
  ('declaracion -> rutina','declaracion',1,'p_declaracion','sintactico.py',34),
  ('constructor_base -> NODO IDENTIFICADOR OBJETO APERTURA bloque_caracteristicas CIERRE','constructor_base',6,'p_constructor_base','sintactico.py',40),
  ('bloque_caracteristicas -> caracteristica','bloque_caracteristicas',1,'p_bloque_caracteristicas','sintactico.py',46),
  ('bloque_caracteristicas -> bloque_caracteristicas caracteristica','bloque_caracteristicas',2,'p_bloque_caracteristicas','sintactico.py',47),
  ('caracteristica -> TIENE APERTURA bloque_tiene CIERRE','caracteristica',4,'p_caracteristica','sintactico.py',56),
  ('caracteristica -> PUEDE APERTURA bloque_puede CIERRE','caracteristica',4,'p_caracteristica','sintactico.py',57),
  ('bloque_tiene -> asignacion','bloque_tiene',1,'p_bloque_tiene','sintactico.py',63),
  ('bloque_tiene -> bloque_tiene asignacion','bloque_tiene',2,'p_bloque_tiene','sintactico.py',64),
  ('asignacion -> assign_type IDENTIFICADOR IGUAL NUMERO','asignacion',4,'p_asignacion','sintactico.py',73),
  ('assign_type -> IDENTIFICADOR','assign_type',1,'p_assign_type','sintactico.py',79),
  ('assign_type -> EJE','assign_type',1,'p_assign_type','sintactico.py',80),
  ('assign_type -> MOTORX','assign_type',1,'p_assign_type','sintactico.py',81),
  ('assign_type -> MOTORY','assign_type',1,'p_assign_type','sintactico.py',82),
  ('bloque_puede -> funcion','bloque_puede',1,'p_bloque_puede','sintactico.py',88),
  ('bloque_puede -> bloque_puede funcion','bloque_puede',2,'p_bloque_puede','sintactico.py',89),
  ('rutina -> RUTINA IDENTIFICADOR APERTURA bloque_puede CIERRE','rutina',5,'p_rutina','sintactico.py',98),
  ('funcion -> IDENTIFICADOR LPAREN argumentos RPAREN','funcion',4,'p_funcion','sintactico.py',104),
  ('argumentos -> argumento','argumentos',1,'p_argumentos','sintactico.py',110),
  ('argumentos -> argumentos COMA argumento','argumentos',3,'p_argumentos','sintactico.py',111),
  ('argumento -> IDENTIFICADOR','argumento',1,'p_argumento','sintactico.py',121),
  ('argumento -> NUMERO','argumento',1,'p_argumento','sintactico.py',122),
  ('modificador_caracteristica -> IDENTIFICADOR TIENE APERTURA bloque_tiene CIERRE','modificador_caracteristica',5,'p_modificador_caracteristica','sintactico.py',128),
  ('modificador_caracteristica -> IDENTIFICADOR PUEDE APERTURA bloque_puede CIERRE','modificador_caracteristica',5,'p_modificador_caracteristica','sintactico.py',129),
]
